### ISSUE TITLE
Print favorite videogames

### ISSUE THREAD

**Issue by LuisRococo** [JuanDiegoPV/Learning-Git#3]
We need to print your favorite video games. 

For that we need to follow the next steps:

- Create a new file called `videogames.py`
- Print three video games you like
- On every print also add a ranking of how much you liked that game in scale 0 to 10

**Example of print**
```python
print("Life is strange Colors - 10/10")
```

**Comment by JuanDiegoPV** [comment]
What branch's name do you recommend me?

**Comment by LuisRococo** [comment]
> What branch's name do you recommend me?

It can be named "add-favorite-videogames"
